---
- name: Cau hinh rsyslog 
  hosts: all
  become: yes
  become_method: sudo
  tasks:
  - name: Cai dat cac goi co ban
    apt:
      name: "{{ packages }}"
      state: present
    vars:
      packages:
      - tar
      - wget
      - unzip
      - rsyslog

  - name: Tao file cau hinh day log ve graylog qua syslog
    template:
      src:  templates/remote.conf.j2
      dest: /etc/rsyslog.d/graylog.conf
      mode: '644'
      owner: root
      group: root
      
  # - name: Khai bao file rsyslog 
    # template:
      # src:  templates/rsyslog-ubuntu.conf.j2
      # dest: /etc/rsyslog.conf
      # mode: '644'
      # owner: root
      # group: root
      
  - name: restart the rsyslog service on remote nodes
    service:
      name: rsyslog
      state: restarted
