---
- name: Cac cau hinh hoan thien may chu
  hosts: 10.10.100.177
  become: yes
  become_method: sudo
  tasks:
  - name: in ra bien
    debug:
      msg: "{{ ansible_hostname }} va {{ansible_default_ipv4.address}}"

  - name: Khai bao file host 
    template:
      src:  templates/hosts.j2
      dest: /etc/hosts

  - name: restart the rsyslog service on remote nodes
    service:
      name: rsyslog
      state: restarted
      
  - name: Cau hinh timezone Asia/Ho_Chi_Minh
    community.general.timezone:
      name: Asia/Ho_Chi_Minh
