---
- name: Config rsyslog for graylog
  hosts: all
  become: yes
  become_method: sudo
  tasks:
  - name: General packages are installed
    apt:
      name: "{{ packages }}"
      state: present
    vars:
      packages:
      - tar
      - wget
      - unzip
      - rsyslog

  - name: create a jinja2 template
    template:
      src:  templates/remote.conf.j2
      dest: /etc/rsyslog.d/graylog.conf
      mode: '644'
      owner: root
      group: root
      
  - name: config rsyslog for cmdlog 
    template:
      src:  templates/rsyslog-ubuntu.conf.j2
      dest: /etc/rsyslog.conf
      mode: '644'
      owner: root
      group: root
      
  - name: restart the rsyslog service on remote nodes
    service:
      name: rsyslog
      state: restarted
